### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by knownasilya** [glimmerjs/glimmer-di#27] opened 2017-02-22 04:42 UTC
I'm getting the following error when attempting to use this lib:

```no-highlight
< /Users/iradchenko/sandbox/core/node_modules/@glimmer/di/dist/commonjs/es5/registry.js:13
<         (0, _babelHelpers.classCallCheck)(this, Registry);
<                                          ^
< TypeError: (0 , _babelHelpers.classCallCheck) is not a function
<     at new Registry (/Users/iradchenko/sandbox/core/node_modules/@glimmer/di/dist/commonjs/es5/registry.js:13
:42)
```

I have `transform-runtime` defined in my Babel plugins.

**Comment by robbiepitts** [comment] 2017-02-22 13:24
@knownasilya I think the problem is that the `babel-helpers` package is not present, presumably because you are not using `@glimmer/build` which is what would include it. If you add the `babel-helpers` package does that resolve your problem? If so I think we'll want to add that to `dependencies` here.

**Comment by knownasilya** [comment] 2017-02-22 13:58
I'll try it again, but from debugging (before adding `babel-helpers`) the value of `_babelHelpers` was an object that could return `_babelHelpers.get('classCallCheck')` which was a function AST.

**Comment by knownasilya** [comment] 2017-02-23 00:54
Just as I remember, adding `babel-helpers` doesn't affect the error one bit 😞

**Comment by dgeb** [comment] 2017-02-23 01:10
Thanks for the error report and example @knownasilya. I'll investigate soon.

**Comment by dgeb** [comment] 2017-03-10 22:13
@knownasilya This _seems_ to be resolved with @glimmer/di v0.1.9, which drops the dependency on @glimmer/util. I'm guessing that there was an issue with the commonjs dist of @glimmer/util@0.21 but I have not verified.

I'm basing my assessment on simply running `npm run build && npm start` successfully. Please close if this looks good to you as well.

**Comment by knownasilya** [comment] 2017-03-10 23:00
Seems to be working

**Comment by knownasilya** [comment] 2017-03-10 23:01
Thanks

**Comment by knownasilya** [comment] 2017-03-11 18:15
Upon a closer look, it seems the issue still persists.

**Comment by dgeb** [comment] 2017-03-16 19:35
@knownasilya I'm pretty sure that just-published @glimmer/di@0.1.11 will resolve this issue for you. For simplicity, @glimmer/build is now inlining babel helpers by default for es5 builds.

Please reopen this issue if you continue to have problems.

**Closed by dgeb** 2017-03-16 19:35 UTC

**Comment by knownasilya** [comment] 2017-03-16 19:58
Fix confirmed 👍

**Comment by dgeb** [comment] 2017-03-16 20:49
Nice - thanks for confirming @knownasilya 💯
